### ISSUE TITLE
hello, I encounter a problem when training, please help me 

### ISSUE THREAD

**Issue by zhengkai17** [hfslyc/AdvSemiSeg#36]
when I train the model on VOC2012, it stops at the 160/20000 .

Traceback (most recent call last):
  File "train.py", line 474, in <module>
    main()
  File "train.py", line 335, in main
    _, batch = trainloader_remain_iter.__next__()
  File "/home/zhengkai/anaconda3/envs/tensorflow/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 572, in __next__
    raise StopIteration
StopIteration

**Comment by hfslyc** [comment]
Hi, it seems that your dataloader has problem during data loading. You might want to check what's the error inside dataloader (like missing file?)
