### ISSUE TITLE
The result on the 0.125 set is different from that in the paper

### ISSUE THREAD

**Issue by bomtorazek** [hfslyc/AdvSemiSeg#46]
In "read me",  you commented that the mean IOU should be around 68.8% for the pre-trained model for 0.125 set (adv+ semi).

However, in the paper the result is 69.5% other than 68.8%. 

Why did you comment that it is around 68.8%? (Actually, the pre-trained weight from you got 69.4% in my computer, not around 68.8%, which is similar with the result of the paper.)

(In addition, when I retrained your code with the batch size of 8 for RTX 2080 Ti.
The result was 68.5%, which is around 68.8%, but I think this is because of the batch size.)

**Comment by Orchid0714** [comment]
@bomtorazek 
I have some problems on training the VOC dataset, the error is as follows.
I don't know how to modify it. can you tell me how to settle this? thank you !

runfile('G:/work_z/AdvSemiSeg-master/train.py', wdir='G:/work_z/AdvSemiSeg-master')
Downloading: "http://vllab1.ucmerced.edu/~whung/adv-semi-seg/resnet101COCO-41f33a49.pth" to C:\Users\Admin/.torch\models\resnet101COCO-41f33a49.pth
168it [00:00, 168012.18it/s]
Traceback (most recent call last):
File "", line 1, in 
runfile('G:/work_z/AdvSemiSeg-master/train.py', wdir='G:/work_z/AdvSemiSeg-master')
File "e:\python\python36\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
execfile(filename, namespace)
File "e:\python\python36\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
exec(compile(f.read(), filename, 'exec'), namespace)
File "G:/work_z/AdvSemiSeg-master/train.py", line 473, in 
main()
File "G:/work_z/AdvSemiSeg-master/train.py", line 206, in main
saved_state_dict = model_zoo.load_url(args.restore_from)
File "e:\python\python36\lib\site-packages\torch\utils\model_zoo.py", line 66, in load_url
_download_url_to_file(url, cached_file, hash_prefix, progress=progress)
File "e:\python\python36\lib\site-packages\torch\utils\model_zoo.py", line 106, in _download_url_to_file
.format(hash_prefix, digest))
RuntimeError: invalid hash value (expected "41f33a49", got "99a66a06aed2ae4b02ddfb0d43c373ade53336020298039578d6187b1f3e8fc2")

**Comment by bomtorazek** [comment]
Sorry, I don't know the reason why the error occurs on your computer. It might be the problem with downloading the weights pre-trained on COCO, so you can download it manually to the appropriate path and run again.

**Comment by Orchid0714** [comment]
yeah, it is my network problem, thank you for replying!

**Comment by lxtGH** [comment]
@bomtorazek Hi Did you reproduce the results ?

**Comment by aoaoaoaoa** [comment]
Why is the mean IOU of the pre-training weight I tested very low(Unreasonably low)?

**Comment by aoaoaoaoa** [comment]
Why is the mean IOU of the pre-trained weight I tested very low(Unreasonably low)?

**Comment by bomtorazek** [comment]
> @bomtorazek Hi Did you reproduce the results ?
Yes, as I mentioned above, I reproduced the results two years ago.
